config/routes.rb
Hidb::Application.routes.draw do
  match 'download' => 'reports#download', :as => :download
  
  resources :internships do
    collection do
    end
    member do
      post :approve
      post :vote_up
      post :vote_down
      post :available
    end
  end

  #resources :internships
  match '/unapproved' => 'internships#unapproved', :as => :unapproved
  match '/opportunities' => 'internships#opportunities', :as => :opportunities
  match '/reviews' => 'internships#reviews', :as => :reviews
  match "/set_type" => "internships#set_type", :as => :set_type, :via => [:post]
  
  
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  match 'authenticate' => 'user_sessions#create', :as => :authenticate, :via => :post
  #match 'signup' => 'users#new', :as => :signup
  match 'connect' => 'users#update', :as => :connect, :via => :post
  match "reset" => "users#detonate"
  resources :users
  resource :user_session
  match 'users(/:id)' => 'users#show', :as => :profile  
  
  match 'register' => 'users#new', :as => :register
  match 'signup' => 'users#create', :as => :signup, :via => :post
  
  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil
  match '/change/:token' => 'users#change_email', :as => :change, :token => nil
  match '/home' => 'users#home', :as => :home
  
  resources :users do
    collection do
      get :top
    end
    member do
      post :make_admin
    end
  end

  match 'feedbacks/new' => 'feedbacks#new', :as => :new_feedback
  match 'feedbacks' => 'feedbacks#create', :as => :feedback
  resources :comments do
  
    member do
  post :destroy
  end
  
  end

  resources :finds do
    collection do
      get :advanced_search
    end
    member do
    end
  end
  match 'advanced_search' => 'finds#advanced_search', :as => :advanced_search
  
  resources :words do
    collection do
      get :random
    end
    member do
      get :add_definition
    end
  end

  resources :definitions do
    collection do
      get :definition_of_the_day
      get :hot
      get :most_recent
      get :news_feed
    end
    member do
      post :add_comment
      post :vote
    end
  end

  match ':controller/auto_complete_for_word_name' => '#auto_complete_for_word_name', :format => 'json'
  match ':controller/:action' => '#index', :as => :auto_complete, :via => :get, :constraints => { :action => /auto_complete_for_\S+/ }

  match "/autocomplete" => "finds#autocomplete", :as => :autocomplete
  
  match "/about" => "info#about", :as => :about
  match "/contact" => "info#contact", :as => :contact
  match "/privacy" => "info#privacy", :as => :privacy
  match "/terms" => "info#terms", :as => :terms
  match "/resume" => "info#resume", :as => :resume
  match "/test" => "info#test", :as => :test
  
  root :to => "internships#index" 

  # match 'controllerinfo' => '#index', :as => :with_options
  # match 'controllergames' => '#index', :as => :with_options
  match '/' => 'info#index'
  match '/:controller(/:action(/:id))'
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_user, :only => [:follow, :unfollow, :edit, :update]
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :admin_only, :only => :detonate

  def index
    @users = User.all
    
    # if params[:term]
    #   #@user_autocomplete = User.find(:all,:conditions => ['name LIKE ? OR login', "%#{params[:term]}%"], :select => "name, login", :limit => 10)
    #   @user_autocomplete = User.find(:all,:conditions => ['LOWER(name) LIKE ? OR LOWER(login) LIKE ?', "%#{params[:term].downcase}%", "%#{params[:term].downcase}%"], :select => "name, login", :limit => 10)
    # end
    
    respond_to do |wants|
      wants.html
      wants.xml  { render :xml => @user_autocomplete }
      wants.json { render :json => @user_autocomplete.to_json }
      wants.csv { send_data @users.to_comma if current_user.admin }
    end
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    # block! see user_sessions_controller.rb for description
    @user.save do |result|
      if result
        flash[:notice] = "Account registered!"
        #redirect_back_or_default profile_url(@user)
        redirect_to edit_user_path(@user)
      else
        flash[:notice] = "Registration failed. Try again."
        redirect_to register_url
      end
    end
  end

  def edit
    @user = @current_user
    @profile = @user.profile
  end
  
  def update
    return create unless @current_user
    @user = @current_user # makes our views "cleaner" and more consistent
    @user.update_attributes(params[:user]) do |result|
      if result
        flash[:notice] = "Account updated!"
        #redirect_to profile_url(@user)
        redirect_to profile_url(@user)
      else
        raise @user.errors.inspect
        render :action => :edit
      end
    end
  end
 
  def destroy
    @user = User.find_by_url(params[:id])
    if @user.nil?
      @user = User.find(params[:id])
    end
    if current_user and @user.id == current_user.id
      @user.destroy
    end

    respond_to do |wants|
      wants.html { redirect_to(root_path) }
      wants.xml  { head :ok }
    end
  end
  
  def detonate
    session.clear
    User.all.collect(&:destroy)
    redirect_to login_url
  end
  
  def show
    @user = User.find_by_url(params[:id])
    if @user.nil?
      @user = User.find(params[:id])
    end

    puts "SESSION: #{session.inspect}"
    puts @current_user.access_tokens.inspect if current_user
    @user_size = User.count
    @profile = @user.profile
  end

  def activate
    logout_keeping_session!
    user = User.find_by_perishable_token(params[:perishable_token]) unless params[:perishable_token].blank?
    case
    when (!params[:perishable_token].blank?) && user
      user.activate!
      user.activation
      flash[:notice] = "Signup complete! Please sign in to continue."
      redirect_to '/login'
    when params[:perishable_token].blank?
      flash[:error] = "The activation code was missing.  Please follow the URL from your email."
      redirect_back_or_default('/')
    else 
      flash[:error]  = "We couldn't find a user with that activation code -- check your email? Or maybe you've already activated -- try signing in."
      redirect_back_or_default('/')
    end
  end
  
  def change_email
    user = User.find_by_perishable_token(params[:perishable_token]) unless params[:perishable_token].blank?
    case
    when (!params[:perishable_token].blank?) && user
      user.email = user.temp
      user.perishable_token = nil
      user.save(false)
      flash[:notice] = "Email successfully changed!"
      redirect_back_or_default('/')
    when params[:perishable_token].blank?
      flash[:error] = "The token was missing.  Please follow the URL from your email."
      redirect_back_or_default('/')
    else 
      flash[:error]  = "We couldn't find a user with that token -- check your email? Or maybe you've already activated -- try signing in."
      redirect_back_or_default('/')
    end
  end
  
  def follow 
    user =  User.find_by_url(params[:user])
    if current_user.following?(user)
      if current_user.stop_following(user)
        flash[:notice] = "You are no longer following #{user.username}"
      else
        flash[:error] = 'Something has gone horribly wrong.'
      end
    else
      if current_user.follow(user)
        flash[:notice] = "You are now following #{user.username}"
      else
        flash[:error] = 'Something has gone horribly wrong.'
      end
    end
    respond_to do |wants|
      wants.html { redirect_to :back }
      wants.xml  { render :xml => @user }
      #wants.js
    end
  end
  
  def make_admin 
    user = User.find(params[:user])
    if user.admin == false
      user.admin = true
      if user.save(false)
        flash[:notice] = "You have made this user an admin"
      else
        flash[:error] = 'Something has gone horribly wrong.'
      end
    else
      user.admin = false
      if user.save(false)
        flash[:notice] = "You have removed admin access for user"
      else
        flash[:error] = 'Something has gone horribly wrong.'
      end
    end
    respond_to do |wants|
      wants.html { redirect_to :back }
      wants.xml  { render :xml => @user }
      #wants.js
    end
  end
 
end

app/helpers/users_helper.rb
module UsersHelper
  
  #
  # Use this to wrap view elements that the user can't access.
  # !! Note: this is an *interface*, not *security* feature !!
  # You need to do all access control at the controller level.
  #
  # Example:
  # <%= if_authorized?(:index,   User)  do link_to('List all users', users_path) end %> |
  # <%= if_authorized?(:edit,    @user) do link_to('Edit this user', edit_user_path) end %> |
  # <%= if_authorized?(:destroy, @user) do link_to 'Destroy', @user, :confirm => 'Are you sure?', :method => :delete end %> 
  #
  #
  def if_authorized?(action, resource, &block)
    if authorized?(action, resource)
      yield action, resource
    end
  end

  #
  # Link to user's page ('users/1')
  #
  # By default, their login is used as link text and link title (tooltip)
  #
  # Takes options
  # * :content_text => 'Content text in place of user.login', escaped with
  #   the standard h() function.
  # * :content_method => :user_instance_method_to_call_for_content_text
  # * :title_method => :user_instance_method_to_call_for_title_attribute
  # * as well as link_to()'s standard options
  #
  # Examples:
  #   link_to_user @user
  #   # => <a href="/users/3" title="barmy">barmy</a>
  #
  #   # if you've added a .name attribute:
  #  content_tag :span, :class => :vcard do
  #    (link_to_user user, :class => 'fn n', :title_method => :login, :content_method => :name) +
  #          ': ' + (content_tag :span, user.email, :class => 'email')
  #   end
  #   # => <span class="vcard"><a href="/users/3" title="barmy" class="fn n">Cyril Fotheringay-Phipps</a>: <span class="email">barmy@blandings.com</span></span>
  #
  #   link_to_user @user, :content_text => 'Your user page'
  #   # => <a href="/users/3" title="barmy" class="nickname">Your user page</a>
  #
  def link_to_user(user, options={})
    raise "Invalid user" unless user
    options.reverse_merge! :content_method => :login, :title_method => :login, :class => :nickname
    content_text      = options.delete(:content_text)
    content_text    ||= user.send(options.delete(:content_method))
    options[:title] ||= user.send(options.delete(:title_method))
    link_to h(content_text), user_path(user), options
  end

  #
  # Link to login page using remote ip address as link content
  #
  # The :title (and thus, tooltip) is set to the IP address 
  #
  # Examples:
  #   link_to_login_with_IP
  #   # => <a href="/login" title="169.69.69.69">169.69.69.69</a>
  #
  #   link_to_login_with_IP :content_text => 'not signed in'
  #   # => <a href="/login" title="169.69.69.69">not signed in</a>
  #
  def link_to_login_with_IP content_text=nil, options={}
    ip_addr           = request.remote_ip
    content_text    ||= ip_addr
    options.reverse_merge! :title => ip_addr
    if tag == options.delete(:tag)
      content_tag tag, h(content_text), options
    else
      link_to h(content_text), login_path, options
    end
  end

  #
  # Link to the current user's page (using link_to_user) or to the login page
  # (using link_to_login_with_IP).
  #
  def link_to_current_user(options={})
    if current_user
      link_to_user current_user, options
    else
      content_text = options.delete(:content_text) || 'not signed in'
      # kill ignored options from link_to_user
      [:content_method, :title_method].each{|opt| options.delete(opt)} 
      link_to_login_with_IP content_text, options
    end
  end

end

app/views/users/_form.html.erb
<div class= "internship-form">
<% semantic_form_for @user, :html => { :id => "styled-form" } do |form| %>
  <% form.inputs "Required", :id => "required" do %>	
	<%= form.input :username, :input_html => {:size => "20%"} %>
	<%= form.input :school, :label => "School", :as => :select, :collection => User::SCHOOL %>
  <% end %>
  <% form.inputs :name => "Optional", :id => "optional" do %>
		<%= form.input :first_name, :input_html => {:size => "20%"} %>
		<%= form.input :last_name, :input_html => {:size=> "20%"} %>
		<%= form.input :email %>
		<%= form.input :major, :as => :select, :collection => User::MAJOR, :input_html => { :style => 'width: 200px;' } %>
		<%= form.input :yog, :label => "Year of graduation (dddd)" %>
		<%= form.input :linkedin, :label => "Link to LinkedIn Profile" %>
  <% end %>
  <% form.buttons do %>
    <%= form.commit_button %>
  <% end %>
<% end %>
</div>

app/views/users/_new.html.haml
%h2 Login or Register!
%form#authentication_form{:action => "/users", :method => :post}
  %fieldset  
    / authentication_method parameter can be set to "oauth" or "open_id"
    %input{:type => :hidden, :name => :authentication_method, :value => :oauth}
    %legend Click your Oauth or OpenID provider.
    .oauth_providers
      %ul
        - %w(google facebook twitter).each do |name|
          %li.oauth_provider
            %img{:src => "/images/icons/#{name}.png"}
            %input{:type => :radio, :id => "#{name}_oauth_provider", :name => :oauth_provider, :value => name}
        .clearfix
  %fieldset
    %legend Or type in your OpenID address
    .openid_address
      %input.nice{:type => :text, :name => "openid_identifier"}
  %input.submit{:name => :submit, :type => :submit, :value => "Subscribe"}/

app/views/users/confirm.html.haml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
    
    <title>Confirm OpenID - Stack Overflow</title>
    <link rel="stylesheet" href="http://sstatic.net/so/all.css?v=0554a32b907e">
    <link rel="shortcut icon" href="http://sstatic.net/so/favicon.ico">
    <link rel="apple-touch-icon" href="http://sstatic.net/so/apple-touch-icon.png">
    <link rel="search" type="application/opensearchdescription+xml" title="Stack Overflow" href="http://sstatic.net/so/opensearch.xml">
    
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
    
    <script type="text/javascript" src="http://sstatic.net/so/js/master.js?v=1efdfca3b527"></script>
    <script type="text/javascript">
    var imagePath='http://sstatic.net/so/img/';
    
    </script>
    

</head>
<body class="user-page">
    <noscript><div id="noscript-padding"></div></noscript>
    <div id="notify-container"></div>

    <div id="custom-header"></div>
    <div class="container">        
        <div id="header">
            <div id="topbar">
                <div id="hlinks">
                    <span id="hlinks-user">
                    <a href="/users/recent/169992" title="you have no new replies"><span class="envelope-off">&nbsp;</span></a> 
                    <a href="/users/169992/viatropos" >viatropos</a>&nbsp;<span class="reputation-score" title="reputation score">4,117</span><span title="2 silver badges"><span class="badge2"></span><span class="badgecount">2</span></span><span title="17 bronze badges"><span class="badge3"></span><span class="badgecount">17</span></span>
<span class="lsep">|</span>

                    </span>
                    <span id="hlinks-nav">
                    <a href="/users/logout?returnurl=%2fusers%2fauthenticate%2f%26dnoa.usersuppliedidentifier%3d%2fprofiles%2flancejpollard%26openid.ns%3d%2fauth%2f2.0%26openid.mode%3did_res%26openid.op_endpoint%3dhttps%3a%2f%2fwww.google.com%2faccounts%2fo8%2fud%3fsource%3dprofiles%26openid.response_nonce%3d2010-05-24t10%3a55%3a17zxe9bg_dzr-tyfg%26openid.return_to%3d%2fusers%2fauthenticate%2f%26dnoa.usersuppliedidentifier%3dhttp%25253a%25252f%25252fwww.google.com%25252fprofiles%25252flancejpollard%26openid.assoc_handle%3daoqobueqfgajhbxscjwqwu6fwfnpcdrlls06iruwdiyip_6-sciwupyk%26openid.signed%3dop_endpoint%2cclaimed_id%2cidentity%2creturn_to%2cresponse_nonce%2cassoc_handle%2cns.ext1%2cext1.mode%2cext1.type.alias4%2cext1.value.alias4%26openid.sig%3d245h1abjqy4naq35pn8rshumbys%3d%26openid.identity%3d%2fprofiles%2flancejpollard%26openid.claimed_id%3d%2fprofiles%2flancejpollard%26openid.ns.ext1%3d%2fsrv%2fax%2f1.0%26openid.ext1.mode%3dfetch_response%26openid.ext1.type.alias4%3d%2fcontact%2femail%26openid.ext1.value.alias4%3dlancejpollard%40gmail.com">log out</a>
<span class="lsep">|</span>

                    </span>
                    <span id="hlinks-custom">
                    <a href="/about">about</a> <span class="lsep">|</span> <a href="/faq">faq</a>
                    </span>
                </div>
                <div id="hsearch">
                    <form id="search" action="/search" method="get">
                    <div>
                        <input name="q" class="textbox" tabindex="1" onfocus="if (this.value=='search') this.value = ''" type="text" maxlength="80" size="28" value="search">
                    </div>
                    </form>
                </div>
            </div>
            <br class="cbt">
            <div id="hlogo">
                <a href="/">Stack Overflow</a>
            </div>
            <div id="hmenus">
                <div class="nav mainnavs">
                    <ul>
                        <li><a id="nav-questions" href="/questions">Questions</a></li>
                        <li><a id="nav-tags" href="/tags">Tags</a></li>
                        <li class="youarehere"><a id="nav-users" href="/users">Users</a></li>
                        <li><a id="nav-badges" href="/badges">Badges</a></li>
                        <li><a id="nav-unanswered" href="/unanswered">Unanswered</a></li>
                    </ul>
                </div>
                <div class="nav askquestion">
                    <ul>
                        <li id="nav-askquestion" >
                            <a href="/questions/ask">Ask Question</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    
        <div id="content">
            
    <div class="subheader">
        <h1>Confirm OpenID</h1>
    </div>
    <div class="page-description">
        <form id="logout-user" action="/users/openidconfirm" method="post">    

            <p>This is an OpenID we haven't seen on Stack Overflow before:</p>
            <p class="openid-identifier" style="font-size: 150%">http://www.google.com/profiles/lancejpollard</p>
            <p>Do you want to associate this OpenID with your Stack Overflow account?</p>
        
            <div>
                <input type="hidden" name="fkey" value="6f37f59453d47f880827ccfc1dadc632">
                <input type="hidden" name="s" value="ed799538-61ce-49bb-9bd4-0d81de548e1e">
                <input type="submit" value="Associate OpenID" style="font-size: 120%">
                <input type="button" value="Cancel" style="font-size: 120%" onclick="window.location.href = 'http://stackoverflow.com/users/169992/viatropos?s=ed799538-61ce-49bb-9bd4-0d81de548e1e'">
            </div>            
        </form>
            
    </div>

        </div>
    </div>
    <div id="footer">
        <div class="footerwrap">
            <div id="footer-menu">
                <a href="/about">about</a> |
                <a href="/faq">faq</a> |
                <a href="http://blog.stackoverflow.com/">blog</a> |
                <a href="http://itc.conversationsnetwork.org/series/stackoverflow.html">podcast</a> |
                <a href="/privacy">privacy policy</a> |
                <a href="http://ads.stackoverflow.com/a.aspx?ZoneID=0&amp;BannerID=323&amp;AdvertiserID=5&amp;CampaignID=194&amp;Task=Click&amp;SiteID=1">advertising info</a> |
                <b><a href="mailto:team@stackoverflow.com">contact us</a></b> |
                <b><a href="http://meta.stackoverflow.com">feedback always welcome</a></b>
                <div id="footer-sites">
                    <span style="color:#FE7A15;font-size:140%">&#9632;</span>&nbsp;<a href="http://stackoverflow.com">stackoverflow.com</a>&nbsp;&nbsp;
                    <span style="color:#FE7A15;font-size:140%">&#9632;</span>&nbsp;<a href="http://stackapps.com">api/apps</a>&nbsp;&nbsp;
                    <span style="color:#FE7A15;font-size:140%">&#9632;</span>&nbsp;<a href="http://careers.stackoverflow.com">careers</a>&nbsp;&nbsp;                    
                    <span style="color:#E8272C;font-size:140%">&#9632;</span>&nbsp;<a href="http://serverfault.com">serverfault.com</a>&nbsp;&nbsp;
                    <span style="color:#00AFEF;font-size:140%">&#9632;</span>&nbsp;<a href="http://superuser.com">superuser.com</a>&nbsp;&nbsp;
                    <span style="color:#969696;font-size:140%">&#9632;</span>&nbsp;<a href="http://meta.stackoverflow.com">meta</a>&nbsp;&nbsp;
                    <a href="http://www.howtogeek.com">howtogeek.com</a>&nbsp;&nbsp;
                    <a href="http://doctype.com">doctype.com</a>
                </div>
            </div>
            <div id="footer-flair">
	            <a href="http://creativecommons.org/licenses/by-sa/2.5/" class="cc-wiki-link"></a>
	            <a href="http://www.peakinternet.com/business/hosting/colocation-dedicated#" class="peak-link"></a>
                <div id="svnrev">revision: 2010.5.24.2</div>
            
            </div>
            <div id="copyright">
                site design / logo &copy; 2010 stackoverflow.com internet services, inc; 
                user contributions licensed under <a href="http://creativecommons.org/licenses/by-sa/2.5/" rel="license">cc-wiki</a> with <a href="http://blog.stackoverflow.com/2009/06/attribution-required/" rel="license">attribution required</a>
            </div>
        </div>
    </div>
    
    <noscript>
        <div id="noscript-warning">Stack Overflow works best with JavaScript enabled<img src="http://pixel.quantserve.com/pixel/p-c1rF4kxgLUzNc.gif" alt="" class="dno"></div>
    </noscript>
    
    <script type="text/javascript">
        document.write(unescape("%3Cscript src='http://www.google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
    </script>
    <script type="text/javascript">
        var pageTracker = _gat._getTracker("UA-5620270-1");
        pageTracker._trackPageview();
    </script>
    <script type="text/javascript">
        _qoptions = { qacct : "p-c1rF4kxgLUzNc" };
    </script>
    <script type="text/javascript" src="http://edge.quantserve.com/quant.js"></script>
        
</body>
</html>

app/views/users/edit.html.erb
<% title "Update Your Profile" %>
<%= "<h2>Hi #{@profile[:name]}!</h2>".html_safe  %>
<p>Please fill out some information about yourself before proceeding</p>

<%= render 'form' %>

app/views/users/new.html.erb
<% title "Sign up"%>

<h2><%=I18n.t("Sign up as a new user")%></h2>
<h1><%=I18n.t("Have an account?")%> <%= link_to I18n.t("Login instead"), login_path %></h1>
<% @user.password = nil %>

<div class="left" id="register-definitious">
  <h3>Create a new <%= SITE_NAME %> account</h3>
	<%= semantic_form_for @user, :url => signup_path do |form| %>
	  <%# form.inputs "Basic", :id => "basic" do %>
	  <% form.inputs do %>
	    <%= form.input :email, :label => I18n.t("email"), :input_html => {:size => 20} %>
	    <%= form.input :login, :label => I18n.t("Username"), :input_html => {:size => 20} %>
			<%= form.input :password, :label => I18n.t("password"), :input_html => {:size => 20} %>
	  <% end %>
	  <%# form.inputs :name => "Advanced Options", :id => "advanced" do %>
	    <%# form.input :slug, :label => "URL Title", :hint => "Created automatically if left blank", :required => false %>
	  <%# end %>
	  <% form.buttons do %>
    	<%= form.commit_button :label => I18n.t("Sign up"), :button_html => { :class => "btn blue" } %>
	  <% end %>
	<% end %>
</div>

<div class="right" id="register-facebook">
<h3><%="Or click on one of these to login or register!"%></h3>
<%= form_for @user, :url => authenticate_path, :html => { :method => :post, :class => "authentication_form" } do |f| %>
<!-- authentication_type should be "user" or "session", based on controller -->
<%= oauth_login_hidden_input %>
  <div class='oauth_providers'>
    <ul>
      <%# %w(google facebook twitter yahoo myspace github).each do |name| %>
      <% %w(google facebook).each do |name| %>
      <li class='oauth_provider'>
        <%= image_tag "/images/icons/#{name}.png" %>
        <%= radio_button_tag :oauth_provider, name %>
      </li>
      <% end %>
    </ul>
  </div>
<% submit_tag "Login", :class => :submit %>
<% end %>
</div>

app/views/users/show.html.erb
<% title (@user.first_name and @user.last_name) ? "#{@user.first_name} #{@user.last_name}'s profile" : "#{@profile[:name]}'s profile" %>

<% if current_user and current_user.id == @user.id %>
	<%= "<h2>Hi #{@profile[:name]}!</h2>".html_safe  %>
	<%# if @user.first_name.nil? or @user.last_name.nil? or @user.email.nil? or @user.major.nil? or @user.yog.nil? %>
	<!-- <p>Please fill out some information about yourself before proceeding</p> -->
	<%# render 'form' %>
	<%# end %>
	
<% else %>
	<% if (@user.first_name and @user.last_name) %>
		<%= "<h2>#{@user.first_name} #{@user.last_name}'s profile</h2>".html_safe %>
	<% else %>
		<%= "<h2>#{@profile[:name]}'s profile</h2>".html_safe %>
	<% end %>
<% end %><p>
	<% if current_user and current_user.admin %>
	<%= link_to "Approve internships!", unapproved_path %>
	<% end %>
<%= link_to "View internships!", internships_path %>
<%= link_to "Create a new internship!", new_internship_path %></p>
<div id="admin-button">
	<% if current_user and current_user.admin == true %>
		<% if @user.admin == false %>
	  	<%= button_to "Make Admin", make_admin_user_path(:user => @user), :method => :post, :remote => true, :class => "btn make_admin", :id => "approve", :onclick => "$('#approve').toggle();$('#unapprove').toggle();" %>
	<%= button_to "Remove as Admin", make_admin_user_path(:user => @user), :method => :post, :remote => true, :class => "btn remove_admin", :id => "unapprove", :onclick => "$('#approve').toggle();$('#unapprove').toggle();", :style => "display:none;" %>
			<% else %>
			<%= button_to "Make Admin", make_admin_user_path(:user => @user), :method => :post, :remote => true, :class => "btn make_admin", :id => "approve", :onclick => "$('#approve').toggle();$('#unapprove').toggle();", :style => "display:none;" %>
			<%= button_to "Remove as Admin", make_admin_user_path(:user => @user), :method => :post, :remote => true, :class => "btn remove_admin", :id => "unapprove", :onclick => "$('#approve').toggle();$('#unapprove').toggle();" %>
			<% end %>
	<% end %>
</div>
<center><%= "Click on edit to add #{itemize_type(@user.blank_fields)}." if current_user and current_user.id == @user.id and !@user.blank_fields.blank? %></center>

<table class="datagrid">
	
	<%="<tr><th>First Name</th><td>#{@user.first_name}</td></tr>".html_safe if !@user.first_name.blank? %>

	<%="<tr><th>Last Name</th><td>#{@user.last_name}</td></tr>".html_safe if !@user.last_name.blank? %>
	<%="<tr><th>Email</th><td>#{@user.email}</td></tr>".html_safe if !@user.email.blank? %>
	<%="<tr><th>Major</th><td>#{@user.major}</td></tr>".html_safe if !@user.major.blank? %>
	<%="<tr><th>Graduation</th><td>#{@user.yog}</td></tr>".html_safe if !@user.yog.blank? %>
	<%="<tr><th>LinkedIn</th><td><a href=#{@user.linkedin.include?("http://") ? @user.linkedin : ("http://" + @user.linkedin) if !@user.linkedin.blank?}>#{@user.linkedin}</a></td></tr>".html_safe if !@user.linkedin.blank? %>
	<%="<tr><th>School</th><td>#{@user.school}</td></tr>".html_safe if !@user.school.blank? %>
	<%="<tr><th>Internships</th><td>".html_safe if !@user.internships.blank? %> 
	<%	@user.internships.each_with_index do |internship, i| %>
	<%=	link_to "#{i + 1}. #{internship.internship_name}<br>".html_safe, internship %>
	<% end %>
	<%="</td></tr>".html_safe if !@user.internships.blank? %>

</table>
<div class="actions">
<% if current_user and current_user.admin %>
Download CSV:
<%= link_to "Internships", internships_path(:format => :csv) %>
<%= link_to "Users", users_path(:format => :csv) %>
<% end %>
</div>
<% if current_user and current_user.id = @user.id %>
<div class="actions">
	<%= link_to 'Edit', edit_user_path(@user) %>
	<%= link_to 'Delete', @user, :confirm => 'Are you sure?', :method => :delete %>
	</div>
<% end %>