config/routes.rb
Hidb::Application.routes.draw do
  match 'download' => 'reports#download', :as => :download
  
  resources :internships do
    collection do
    end
    member do
      post :approve
      post :vote_up
      post :vote_down
      post :available
    end
  end

  #resources :internships
  match '/unapproved' => 'internships#unapproved', :as => :unapproved
  match '/opportunities' => 'internships#opportunities', :as => :opportunities
  match '/reviews' => 'internships#reviews', :as => :reviews
  match "/set_type" => "internships#set_type", :as => :set_type, :via => [:post]
  
  
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  match 'authenticate' => 'user_sessions#create', :as => :authenticate, :via => :post
  #match 'signup' => 'users#new', :as => :signup
  match 'connect' => 'users#update', :as => :connect, :via => :post
  match "reset" => "users#detonate"
  resources :users
  resource :user_session
  match 'users(/:id)' => 'users#show', :as => :profile  
  
  match 'register' => 'users#new', :as => :register
  match 'signup' => 'users#create', :as => :signup, :via => :post
  
  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil
  match '/change/:token' => 'users#change_email', :as => :change, :token => nil
  match '/home' => 'users#home', :as => :home
  
  resources :users do
    collection do
      get :top
    end
    member do
      post :make_admin
    end
  end

  match 'feedbacks/new' => 'feedbacks#new', :as => :new_feedback
  match 'feedbacks' => 'feedbacks#create', :as => :feedback
  resources :comments do
  
    member do
  post :destroy
  end
  
  end

  resources :finds do
    collection do
      get :advanced_search
    end
    member do
    end
  end
  match 'advanced_search' => 'finds#advanced_search', :as => :advanced_search
  
  resources :words do
    collection do
      get :random
    end
    member do
      get :add_definition
    end
  end

  resources :definitions do
    collection do
      get :definition_of_the_day
      get :hot
      get :most_recent
      get :news_feed
    end
    member do
      post :add_comment
      post :vote
    end
  end

  match ':controller/auto_complete_for_word_name' => '#auto_complete_for_word_name', :format => 'json'
  match ':controller/:action' => '#index', :as => :auto_complete, :via => :get, :constraints => { :action => /auto_complete_for_\S+/ }

  match "/autocomplete" => "finds#autocomplete", :as => :autocomplete
  
  match "/about" => "info#about", :as => :about
  match "/contact" => "info#contact", :as => :contact
  match "/privacy" => "info#privacy", :as => :privacy
  match "/terms" => "info#terms", :as => :terms
  match "/resume" => "info#resume", :as => :resume
  match "/test" => "info#test", :as => :test
  
  root :to => "internships#index" 

  # match 'controllerinfo' => '#index', :as => :with_options
  # match 'controllergames' => '#index', :as => :with_options
  match '/' => 'info#index'
  match '/:controller(/:action(/:id))'
end

app/views/shared/_head.haml
/ meta
%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "content-type"}/
%meta{:content => "", :name => "description"}/
%meta{:content => "UA-15601175-9", :name => "google-analytics"}/
= yield :meta_head

/ stylesheets
%link{:href => "/stylesheets/reset.css", :media => "screen", :rel => "stylesheet", :type => "text/css"}/
%link{:href => "/stylesheets/application.css", :rel => "stylesheet", :type => "text/css"}/
= yield :stylesheet_head

/ javascripts
- %w(cufon.yui kievit).each do |javascript|
  = javascript_include_tag "/javascripts/#{javascript}.js"
= javascript_include_tag "application"
= yield :javascript_head

= yield :extra_head

app/views/shared/_logo.haml
#logo
  %a{:href => "/internships"}
    %img{:alt => "The Internship Database", :src => "/images/logo.png"}/

app/views/shared/_search.html.erb
<div class="search">
	<%= form_tag(finds_path, :method => 'get') do %>
	<%= text_field_tag(:word, "Search...", :onFocus => "if(this.value==this.defaultValue) this.value='';", :onBlur  => "if(this.value=='') this.value=this.defaultValue;", :id => 'word_search') %>
	<%= image_submit_tag("search.png", :onmouseover => "this.src='/images/search-hover.png'", :onmouseout => "this.src='/images/search.png'", :id => 'searchsubmit', :alt => "Search!") %>
	<% end %>
</div>