config/routes.rb
Hidb::Application.routes.draw do
  match 'download' => 'reports#download', :as => :download
  
  resources :internships do
    collection do
    end
    member do
      post :approve
      post :vote_up
      post :vote_down
      post :available
    end
  end

  #resources :internships
  match '/unapproved' => 'internships#unapproved', :as => :unapproved
  match '/opportunities' => 'internships#opportunities', :as => :opportunities
  match '/reviews' => 'internships#reviews', :as => :reviews
  match "/set_type" => "internships#set_type", :as => :set_type, :via => [:post]
  
  
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  match 'authenticate' => 'user_sessions#create', :as => :authenticate, :via => :post
  #match 'signup' => 'users#new', :as => :signup
  match 'connect' => 'users#update', :as => :connect, :via => :post
  match "reset" => "users#detonate"
  resources :users
  resource :user_session
  match 'users(/:id)' => 'users#show', :as => :profile  
  
  match 'register' => 'users#new', :as => :register
  match 'signup' => 'users#create', :as => :signup, :via => :post
  
  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil
  match '/change/:token' => 'users#change_email', :as => :change, :token => nil
  match '/home' => 'users#home', :as => :home
  
  resources :users do
    collection do
      get :top
    end
    member do
      post :make_admin
    end
  end

  match 'feedbacks/new' => 'feedbacks#new', :as => :new_feedback
  match 'feedbacks' => 'feedbacks#create', :as => :feedback
  resources :comments do
  
    member do
  post :destroy
  end
  
  end

  resources :finds do
    collection do
      get :advanced_search
    end
    member do
    end
  end
  match 'advanced_search' => 'finds#advanced_search', :as => :advanced_search
  
  resources :words do
    collection do
      get :random
    end
    member do
      get :add_definition
    end
  end

  resources :definitions do
    collection do
      get :definition_of_the_day
      get :hot
      get :most_recent
      get :news_feed
    end
    member do
      post :add_comment
      post :vote
    end
  end

  match ':controller/auto_complete_for_word_name' => '#auto_complete_for_word_name', :format => 'json'
  match ':controller/:action' => '#index', :as => :auto_complete, :via => :get, :constraints => { :action => /auto_complete_for_\S+/ }

  match "/autocomplete" => "finds#autocomplete", :as => :autocomplete
  
  match "/about" => "info#about", :as => :about
  match "/contact" => "info#contact", :as => :contact
  match "/privacy" => "info#privacy", :as => :privacy
  match "/terms" => "info#terms", :as => :terms
  match "/resume" => "info#resume", :as => :resume
  match "/test" => "info#test", :as => :test
  
  root :to => "internships#index" 

  # match 'controllerinfo' => '#index', :as => :with_options
  # match 'controllergames' => '#index', :as => :with_options
  match '/' => 'info#index'
  match '/:controller(/:action(/:id))'
end

app/controllers/internships_controller.rb
class InternshipsController < ApplicationController
  before_filter :require_user, :only => [:create, :update, :destroy, :new]
  before_filter :require_admin, :only => [:unapproved]
  # GET /internships
  # GET /internships.xml
  def index    
    @internships = Internship.sort params
    @internships = @internships.collect{|x| x }

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @internships }
      format.csv { send_data Internship.all.to_comma if current_user.admin }
    end
  end

  # GET /internships/1
  # GET /internships/1.xml
  def show
    @internship = Internship.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @internship }
    end
  end

  # GET /internships/new
  # GET /internships/new.xml
  def new
    @internship = Internship.new
    @user = current_user if current_user

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @internship }
    end
  end

  # GET /internships/1/edit
  def edit
    @internship = Internship.find(params[:id])
  end

  # POST /internships
  # POST /internships.xml
  def create
    @internship = Internship.new(params[:internship])
    @internship.user_id = current_user.id

    respond_to do |format|
      if @internship.save
        format.html { redirect_to(internships_path, :notice => 'Internship was successfully created.') }
        format.xml  { render :xml => @internship, :status => :created, :location => @internship }
      else
        flash[:error] = @internship.errors.full_messages.join("<br>")
        format.html { render :action => "new" }
        format.xml  { render :xml => @internship.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /internships/1
  # PUT /internships/1.xml
  def update
    @internship = Internship.find(params[:id])

    respond_to do |format|
      if current_user and @internship.user_id == current_user.id and @internship.update_attributes(params[:internship])
        format.html { redirect_to(@internship, :notice => 'Internship was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @internship.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /internships/1
  # DELETE /internships/1.xml
  def destroy
    @internship = Internship.find(params[:id])
    if current_user and @internship.user_id == current_user.id
      @internship.destroy
    end

    respond_to do |format|
      format.html { redirect_to(internships_url) }
      format.xml  { head :ok }
    end
  end
  
  def unapproved    
    @internships = Internship.find(:all, :conditions => {:approved => false})

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @internships }
    end
  end
  
  def approve 
    internship = Internship.find(params[:internship])
    if internship.approved == false
      internship.approved = true
      if internship.save(false)
        flash[:notice] = "You have approved this internship"
      else
        flash[:error] = 'Something has gone horribly wrong.'
      end
    else
      internship.approved = false
      if internship.save(false)
        flash[:notice] = "You have unapproved this internship"
      else
        flash[:error] = 'Something has gone horribly wrong.'
      end
    end
    respond_to do |wants|
      wants.html { redirect_to :back }
      wants.xml  { render :xml => @user }
      #wants.js
    end
  end
  
  def vote_up 
    if current_user
    internship = Internship.find(params[:internship])
    user = current_user
    
    if !user.voted_for?(internship)
      user.vote_for(internship)
      
      if internship.save(false)
        flash[:notice] = "Thanks for the info!"
      else
        flash[:error] = 'Something has gone horribly wrong.'
      end
    else
      user.unvote(internship)
      
      if internship.save(false)
        flash[:notice] = "Thanks for the info!"
      else
        flash[:error] = 'Something has gone horribly wrong.'
      end
    end
    respond_to do |wants|
      wants.html { redirect_to :back }
      wants.xml  { render :xml => @user }
      wants.js {
        render(:update) {|page| page.replace_html 'votes', :partial => 'internships/votes', :locals => {:internship => internship}}
      }
    end
  else
    respond_to do |wants|
      wants.html { redirect_to :back }
      wants.xml  { render :xml => @user }
      wants.js {
        render(:update) {|page| page.replace_html 'register', :partial => 'user_sessions/form', :locals => {:@user_session => UserSession.new}}
      }
    end
  end
  end
  
  def vote_down 
    if current_user
    internship = Internship.find(params[:internship])
    user = current_user
    
    if !user.voted_against?(internship)
      user.vote_against(internship)
      
      if internship.save(false)
        flash[:notice] = "Thanks for the info!"
      else
        flash[:error] = 'Something has gone horribly wrong.'
      end
    else
      user.unvote(internship)
      
      if internship.save(false)
        flash[:notice] = "Thanks for the info!"
      else
        flash[:error] = 'Something has gone horribly wrong.'
      end
    end
    respond_to do |wants|
      wants.html { redirect_to :back }
      wants.xml  { render :xml => @user }
      wants.js {
        render(:update) {|page| page.replace_html 'votes', :partial => 'internships/votes', :locals => {:internship => internship}}
      }
    end
    else
      respond_to do |wants|
        wants.html { redirect_to :back }
        wants.xml  { render :xml => @user }
        wants.js {
          render(:update) {|page| page.replace_html 'register', :partial => 'user_sessions/form', :locals => {:@user_session => UserSession.new}}
        }
      end
    end
  end
  
  def available 
    internship = Internship.find(params[:internship])
    user = current_user
    
    if internship.available
      internship.available = false
      
      if internship.save(false)
        flash[:notice] = "Thanks for the info!"
      else
        flash[:error] = 'Something has gone horribly wrong.'
      end
    else
      internship.available = true
      
      if internship.save(false)
        flash[:notice] = "Thanks for the info!"
      else
        flash[:error] = 'Something has gone horribly wrong.'
      end
    end
    respond_to do |wants|
      wants.html { redirect_to :back }
      wants.xml  { render :xml => @user }
      wants.js {
        render(:update) {|page| page.replace_html 'votes', :partial => 'internships/votes', :locals => {:internship => internship}}
      }
    end

  end
  
  def opportunities    
    @internships = Internship.sort params
    @internships = @internships.collect{|x| x if x.available}

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @internships }
      format.csv { send_data @internships.all.to_comma if current_user.admin }
    end
  end
  
  def reviews    
    @internships = Internship.sort params
    @internships = @internships.collect{|x| x if x.past}
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @internships }
      format.csv { send_data Internship.all.to_comma if current_user.admin }
    end
  end
  
  def set_type 
    fields = ["semester", "year", "industry", "company_name", "job_field", "city", "state", "country", "website", "responsibilities", "review", "description", "requirements", "paid", "full_time", "search_string", "deadline", "available", "past", "name"]
    internship = Internship.new
    fields.each do |x| 
      eval("internship.#{x}=params[:internship][:#{x}]") if eval("internship.#{x}")
    end
    past = eval(params[:past])
    respond_to do |wants|
      wants.html { redirect_to :back }
      wants.xml  { render :xml => @user }
      wants.js {
        render(:update) {|page| page.replace_html 'form', :partial => 'internships/form', :locals => {:@internship => internship, :past => past}}
      }
    end
  end
  

end

app/helpers/internships_helper.rb
module InternshipsHelper
end

app/views/internships/_form.html.erb
<p>Please provide the details of your internship</p>
<div class="internship-form">
	<% past = @internship.past if past.nil? %>  
<%= semantic_form_for @internship, :html => { :id => "styled-form" } do |form| %>
  <% form.inputs "Required", :id => "required" do %>	
		<%= form.input :available, :input_html => { :checked => "checked" } if past == false %>
		<%= form.input :company_name, :label => "Company/Employer Name", :required => true %>
		<%= form.input :description %>
		<%= form.input :semester, :as => :check_boxes, :collection => Internship::SEMESTER %>
		<%= form.input :year, :as => :select, :collection => Internship::YEAR if past %>
		<%= form.input :year, :as => :select, :selected => Time.now.year, :collection => Internship::YEAR if past == false %>
		<%= form.input :job_field, :as => :select, :collection => Internship::JOB_FIELD, :input_html => { :style => 'width: 200px;' } %>
		<%= form.input :paid, :label => "Compensation", :as => :radio, :collection => {"Paid" => 't', "Unpaid" => 'f'}.sort.reverse %>
		<%= form.input :full_time, :label => "Commitment", :as => :radio, :collection => {"Full-time" => 't', "Part-time" => 'f'}.sort.reverse %>
		<% @internship.deadline = Date.today + 2.months if (@internship.deadline.blank? and past == false) %>
		<%= form.input :deadline if past == false %>
		<%= form.input :review if past %>
		<%= form.input :past, :value => "true", :as => :hidden if past %>
		<%= form.input :available, :value => "false", :as => :hidden if past %>
		<%= form.input :past, :value => "false", :as => :hidden if past == false %>
  <% end %>
  <% form.inputs :name => "Optional", :id => "optional" do %>
	<%= form.input :name, :label => "Internship Name" %>
	<%= form.input :school, :label => "Student Restriction", :as => :select, :collection => User::SCHOOL if past == false %>
	<%= form.input :city %>
	<%= form.input :state, :as => :select, :collection => Internship::STATE %>
	<%= form.input :country, :as => :select, :selected => "United States", :collection => Internship::COUNTRY %>
	<%= form.input :requirements, :label => "Skills/Requirements" if past == false %>
	<%= form.input :responsibilities %>
	<%= form.input :industry, :as => :select, :collection => Internship::INDUSTRY, :input_html => { :style => 'width: 200px;' } %>
	<%= form.input :website, :label => "Organization website" %>
  <% end %>
  <% form.buttons do %>
    <%= form.commit_button %>
  <% end %>
<% end %>
</div>

app/views/internships/_internship_list.html.erb
<% if !internships.blank? %>
<%= link_to("Download", :internships => internships, :format => :csv) if current_user and current_user.admin %>

<table class="datagrid">
  <tr>
	<th><%= link_to "Date submitted", sort_url("sort", "created_at") %></th>
	<th><%= link_to "Company Name", sort_url("sort", "company_name") %></th>
    <th><%= link_to "Field", sort_url("sort", "job_field") %></th>
    <th><%= link_to "City", sort_url("sort", "city") %></th>
    <th><%= link_to "State", sort_url("sort", "state") %></th>
<th><%= link_to "Semester", sort_url("sort", "semester") %></th>
<th><%= link_to "Year", sort_url("sort", "year") %></th>
<th>Type</th>
<th>Poster</th>
<th>More Info</th>
  </tr>

<% internships.each do |internship| %>
<% if internship %>
  <tr>
	<td><%= (Time.now - internship.created_at < 86400) ? "#{time_ago_in_words((Time.now - internship.created_at).seconds.ago)} ago" : internship.created_at.strftime("%b %e, %Y") if internship.created_at %></td>
	<td><%= internship.company_name if internship.company_name %></td>
	<td><%= internship.job_field if internship.job_field %></td>
	<td><%= internship.city if internship.city %></td>
	<td><%= internship.state if internship.state %></td>
	<td><%= internship.semester if internship.semester %></td>
	<td><%= internship.year if internship.year %></td>
	<td><%= internship.past ? "Review" : internship.available ? "Opportunity" : (Time.now < internship.deadline) ? "Position Filled" : "Deadline past" %></td>
	<td><%= link_to "#{internship.user.first_name} #{internship.user.last_name}", internship.user if internship.user %></td>
	<td><%= link_to "Show", internship %></td>
    <!-- <td><%# link_to 'Show', internship %></td>
        <td><%# link_to 'Edit', edit_internship_path(internship) %></td>
        <td><%# link_to 'Destroy', internship, :confirm => 'Are you sure?', :method => :delete %></td> -->
  </tr>
<% end %>
<% end %>
</table>

<br />

<%# link_to 'New Internship', new_internship_path %>

<% else %>
<center><%= "Sorry. We did not find any internships matching your request." %></center>
<% end %>

app/views/internships/_unapproved_internship_list.html.erb
<table class="datagrid">
  <tr>
    <th><%= link_to "Field/Industry", sort_url("sort", "industry") %></th>
    <th><%= link_to "City", sort_url("sort", "city") %></th>
    <th><%= link_to "State", sort_url("sort", "state") %></th>
<th><%= link_to "Company Name", sort_url("sort", "company_name") %></th>
<th><%= link_to "Field", sort_url("sort", "job_field") %></th>
<th><%= link_to "Semester", sort_url("sort", "semester") %></th>
<th><%= link_to "Year", sort_url("sort", "year") %></th>
<th>Student</th>
<th>More Info</th>
<th>Approve</th>
  </tr>

<% internships.each_with_index do |internship, i| %>
  <tr>
		<td><%= internship.industry if internship.industry %>
	<td><%= internship.city if internship.city %></td>
	<td><%= internship.state if internship.state %></td>
	<td><%= internship.company_name if internship.company_name %></td>
	<td><%= internship.job_field if internship.job_field %></td>
	<td><%= internship.semester if internship.semester %></td>
	<td><%= internship.year if internship.year %></td>
	<td><%= link_to "#{internship.user.first_name} #{internship.user.last_name}", internship.user if internship.user %></td>
	<td><%= link_to "Show", internship %></td>
	<td>
	<% if current_user and current_user.admin == true %>
		<% if internship.approved == false %>
	  	<%= button_to "Approve", "/internships/#{internship.id}/approve?internship=#{internship.id}", :method => :post, :remote => true, :class => "btn approve", :id => "approve#{i}", :onclick => "$('#approve#{i}').toggle();$('#unapprove#{i}').toggle();" %>
	<%= button_to "Unapprove",  "/internships/#{internship.id}/approve?internship=#{internship.id}", :method => :post, :remote => true, :class => "btn unapprove", :id => "unapprove#{i}", :onclick => "$('#approve#{i}').toggle();$('#unapprove#{i}').toggle();", :style => "display:none;" %>
			<% else %>
			<%= button_to "Approve",  "/internships/#{internship.id}/approve?internship=#{internship.id}", :method => :post, :remote => true, :class => "btn approve", :id => "approve#{i}", :onclick => "$('#approve#{i}').toggle();$('#unapprove#{i}').toggle();", :style => "display:none;" %>
			<%= button_to "Unapprove",  "/internships/#{internship.id}/approve?internship=#{internship.id}", :method => :post, :remote => true, :class => "btn unapprove", :id => "unapprove#{i}", :onclick => "$('#approve#{i}').toggle();$('#unapprove#{i}').toggle();" %>
			<% end %>
	<% end %>
	</td>
    <!-- <td><%# link_to 'Show', internship %></td>
        <td><%# link_to 'Edit', edit_internship_path(internship) %></td>
        <td><%# link_to 'Destroy', internship, :confirm => 'Are you sure?', :method => :delete %></td> -->
  </tr>
<% end %>
</table>

<br />

<%# link_to 'New Internship', new_internship_path %>

app/views/internships/_votes.html.erb
<div id="message"><%= (current_user and current_user.voted_for?(internship)) ? internship.past ? "".html_safe : "You have applied<br>".html_safe : internship.past ? '' : "You have not applied yet<br>".html_safe  %></div>
<%= (pluralize(internship.votes_for, "person") + (internship.past ? (internship.votes_for == 1) ? " finds this helpful<br>" : " find this helpful<br>" : (internship.votes_for == 1) ? " has applied<br>" : " have applied<br>")).html_safe  %>
<%= (pluralize(internship.votes_against, "person") + ((internship.votes_against == 1) ? " has flagged this<br>" : " have flagged this<br>")).html_safe  %>
<div class="centered-buttons" id="vote-buttons">
  	<li><%= button_to internship.past ?  "Helpful" : "Applied?", vote_up_internship_path(:internship => internship), :method => :post, :remote => true, :class => ((current_user and !current_user.voted_for?(internship)) or !current_user) ? "btn vote_up" : "btn voted", :id => "approve" %></li>
	<% if current_user and current_user.id == internship.user_id and !internship.past %>
	<li><%= button_to "Position filled", available_internship_path(:internship => internship), :method => :post, :remote => true, :class => (current_user and internship.available) ? "btn vote_down" : "btn voted", :id => "approve" %></li>
  	<% else %>
  	<li><%= button_to "Flag", vote_down_internship_path(:internship => internship), :method => :post, :remote => true, :class => ((current_user and !current_user.voted_against?(internship)) or !current_user) ? "btn vote_down" : "btn voted", :id => "approve" %></li>
	<% end %>
</div>

app/views/internships/edit.html.erb
<h1>Editing internship</h1>

<%= render 'form' %>

<%= link_to 'Show', @internship %> |
<%= link_to 'Back', internships_path %>

app/views/internships/index.html.erb
<% title "Internship List" %>

<h2>Internship List</h2>

<p><%= link_to "Create a new internship!", new_internship_path %></p>

<%= render :partial => 'internships/internship_list', :locals => {:internships => @internships} %>

app/views/internships/new.html.erb
<h2>Internship Form</h2>
<% if current_user and current_user.required  %>
<div id="select-type">
	<% if !@internship.changed? %>
<p>Please select the type of internship you are submitting<p>
	<% end %></div>
<div class="centered-buttons">
<li><%= button_to "Opportunity", set_type_path(:past => "false", :internship => @internship.changes), :method => :post, :remote => true, :class => "btn opportunity", :id => "approve", :onclick => "$('#select-type').hide();" %></li>
<li><%= button_to "Past", set_type_path(:past => "true", :internship => @internship.changes), :method => :post, :remote => true, :class => "btn past", :id => "unapprove", :onclick => "$('#select-type').hide();" %></li>
</div>
<div id="form">
	<% if @internship.changed? %>
	<%= render :partial => 'internships/form', :locals => {:@internship => @internship} %>
	<% end %>
</div>
<%# render 'form' %>
<% else %>
<p>Please fill out some information about yourself before proceeding</p>
<%= render 'users/form' %>
<% end %>


<%# link_to 'Back', internships_path %>

app/views/internships/opportunities.html.erb
<% title "Current Internship Opportunities" %>

<h2>Current Internship Opportunities</h2>

<p><%= link_to "Create a new internship!", new_internship_path %></p>

<%= render :partial => 'internships/internship_list', :locals => {:internships => @internships} %>

app/views/internships/reviews.html.erb
<% title ">Past Internship Reviews" %>

<h2>Past Internship Reviews</h2>

<p><%= link_to "Create a new internship!", new_internship_path %></p>

<%= render :partial => 'internships/internship_list', :locals => {:internships => @internships} %>

app/views/internships/show.html.erb
<% title "#{@internship.company_name}" if @internship.company_name %>

<!-- <p id="notice"><%# notice %></p> -->
<div id="register"></div>
<div id="approve-button">
	<%# if current_user and current_user.admin == true %>
		<%# if @internship.approved == false %>
	  	<%# button_to "Approve", approve_internship_path(:internship => @internship), :method => :post, :remote => true, :class => "btn approve", :id => "approve", :onclick => "$('#approve').toggle();$('#unapprove').toggle();" %>
	<%# button_to "Unapprove", approve_internship_path(:internship => @internship), :method => :post, :remote => true, :class => "btn unapprove", :id => "unapprove", :onclick => "$('#approve').toggle();$('#unapprove').toggle();", :style => "display:none;" %>
			<%# else %>
			<%# button_to "Approve", approve_internship_path(:internship => @internship), :method => :post, :remote => true, :class => "btn approve", :id => "approve", :onclick => "$('#approve').toggle();$('#unapprove').toggle();", :style => "display:none;" %>
			<%# button_to "Unapprove", approve_internship_path(:internship => @internship), :method => :post, :remote => true, :class => "btn unapprove", :id => "unapprove", :onclick => "$('#approve').toggle();$('#unapprove').toggle();" %>
			<%# end %>
	<%# end %>	
	<%# if current_user and current_user.admin == true %>
	<%# end %>
</div>
<div class="internship-wrapper">
<div class="internship-summary">
  <h1> Internship Summary </h1>
<div id="votes">
	<%= render :partial => 'internships/votes', :locals => {:internship => @internship} %>
</div>
  <dl>
	<%= "<dt>Date Submitted</dt><dd>#{@internship.created_at.strftime("%b %e, %Y")}</dd>".html_safe if @internship.created_at %>
	<%= "<dt>Deadline</dt><dd>#{@internship.deadline.strftime("%b %e, %Y")}</dd>".html_safe if !@internship.deadline.blank? %>
	<%= "<dt>Company/Employer Name</dt><dd>#{@internship.company_name}</dd>".html_safe if !@internship.company_name.blank? %>
	<%= "<dt>Location</dt><dd>#{@internship.city if !@internship.city.blank?}#{',' if (!@internship.city.blank? and !@internship.state.blank?)} #{@internship.state if !@internship.state.blank?}</dd>".html_safe if !@internship.city.blank? or !@internship.state.blank? %>
	<%= "<dt>Company/Employer Website</dt><dd><a href=#{@internship.website.include?("http://") ? @internship.website : ("http://" + @internship.website) if !@internship.website.blank?}>#{@internship.website}</a></dd>".html_safe if !@internship.website.blank? %>
    <%= "<dt>Industry</dt><dd>#{@internship.industry}</dd>".html_safe if !@internship.industry.blank? %>
    <%= "<dt>Field</dt><dd>#{@internship.job_field}</dd>".html_safe if !@internship.job_field.blank? %> 
	<%= "<dt>Compensation</dt><dd>#{@internship.paid ? "Paid" : "Unpaid"}</dd>".html_safe unless @internship.paid.nil? %>
	<%= "<dt>Commitment</dt><dd>#{@internship.full_time ? "Full-time" : "Part-time"}</dd>".html_safe unless @internship.full_time.nil? %>
</div>
<div class="internship-section">
<div class="internship-main"> 
  <h1><%= @internship.internship_name %><%= @internship.past ? " (Review)" : @internship.available ? "" : (Time.now < @internship.deadline) ? " (Position Filled)" : " (Deadline past)" %></h1>
  <%= "<dt>Description</dt><dl>#{simple_format(@internship.description, :class => 'simple-format')}</dl>".html_safe if !@internship.description.blank? %>
  <%= "<dt>Responsibilities</dt><dl>#{simple_format(@internship.responsibilities, :class => 'simple-format')}</dl>".html_safe if !@internship.responsibilities.blank? %>  
  <%= "<dt>Skills/Requirements</dt><dl>#{simple_format(@internship.requirements, :class => 'simple-format')}</dl>".html_safe if !@internship.past and !@internship.requirements.blank? %>
  <%= "<dt>Review</dt><dl>#{simple_format(@internship.review.html_safe, :class => 'simple-format')}</dl>".html_safe if @internship.past and !@internship.review.blank? %>
	<br>

</div>
<div class="internship-summary" id="poster">
	<h1><%= @internship.past ? "Intern" : "Poster" %></h1>
	<%= "<dt>Name:</dt><dd>#{link_to "#{@internship.user.first_name} #{@internship.user.last_name}", @internship.user}</dd>".html_safe if !@internship.user.blank? %>
	<%= "<dt>School:</dt><dd>#{@internship.user.school}</dd>".html_safe if !@internship.user.school.blank? %>
	<%= "<dt>Year of Graduation:</dt><dd>#{@internship.user.yog}</dd>".html_safe if !@internship.user.yog.blank? %>
	<%= "<dt>Major:</dt><dd>#{@internship.user.major}</dd>".html_safe if !@internship.user.major.blank? %>
	<%= "<dt>LinkedIn:</dt><dd><a href=#{@internship.user.linkedin.include?("http://") ? @internship.user.linkedin : ("http://" + @internship.user.linkedin) if !@internship.user.linkedin.blank?}>#{@internship.user.linkedin}</a></dd>".html_safe if !@internship.user.linkedin.blank? %>

</div>
</div>
</div>
<% if current_user and current_user.id == @internship.user_id %>
	<%= link_to 'Edit', edit_internship_path(@internship) %>
	<%= link_to 'Delete', @internship, :confirm => 'Are you sure?', :method => :delete %>
<% end %>

app/views/internships/unapproved.html.erb
<% title "Unapproved Internships" %>

<h2>Unapproved Internships</h2>

<% if @internships.blank? %>
<p>There are no internships that currently need to be approved</p>
<% else %>
<%= render :partial => 'internships/unapproved_internship_list', :locals => {:internships => @internships} %>
<% end %>