config/routes.rb
Hidb::Application.routes.draw do
  match 'download' => 'reports#download', :as => :download
  
  resources :internships do
    collection do
    end
    member do
      post :approve
      post :vote_up
      post :vote_down
      post :available
    end
  end

  #resources :internships
  match '/unapproved' => 'internships#unapproved', :as => :unapproved
  match '/opportunities' => 'internships#opportunities', :as => :opportunities
  match '/reviews' => 'internships#reviews', :as => :reviews
  match "/set_type" => "internships#set_type", :as => :set_type, :via => [:post]
  
  
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  match 'authenticate' => 'user_sessions#create', :as => :authenticate, :via => :post
  #match 'signup' => 'users#new', :as => :signup
  match 'connect' => 'users#update', :as => :connect, :via => :post
  match "reset" => "users#detonate"
  resources :users
  resource :user_session
  match 'users(/:id)' => 'users#show', :as => :profile  
  
  match 'register' => 'users#new', :as => :register
  match 'signup' => 'users#create', :as => :signup, :via => :post
  
  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil
  match '/change/:token' => 'users#change_email', :as => :change, :token => nil
  match '/home' => 'users#home', :as => :home
  
  resources :users do
    collection do
      get :top
    end
    member do
      post :make_admin
    end
  end

  match 'feedbacks/new' => 'feedbacks#new', :as => :new_feedback
  match 'feedbacks' => 'feedbacks#create', :as => :feedback
  resources :comments do
  
    member do
  post :destroy
  end
  
  end

  resources :finds do
    collection do
      get :advanced_search
    end
    member do
    end
  end
  match 'advanced_search' => 'finds#advanced_search', :as => :advanced_search
  
  resources :words do
    collection do
      get :random
    end
    member do
      get :add_definition
    end
  end

  resources :definitions do
    collection do
      get :definition_of_the_day
      get :hot
      get :most_recent
      get :news_feed
    end
    member do
      post :add_comment
      post :vote
    end
  end

  match ':controller/auto_complete_for_word_name' => '#auto_complete_for_word_name', :format => 'json'
  match ':controller/:action' => '#index', :as => :auto_complete, :via => :get, :constraints => { :action => /auto_complete_for_\S+/ }

  match "/autocomplete" => "finds#autocomplete", :as => :autocomplete
  
  match "/about" => "info#about", :as => :about
  match "/contact" => "info#contact", :as => :contact
  match "/privacy" => "info#privacy", :as => :privacy
  match "/terms" => "info#terms", :as => :terms
  match "/resume" => "info#resume", :as => :resume
  match "/test" => "info#test", :as => :test
  
  root :to => "internships#index" 

  # match 'controllerinfo' => '#index', :as => :with_options
  # match 'controllergames' => '#index', :as => :with_options
  match '/' => 'info#index'
  match '/:controller(/:action(/:id))'
end

app/views/layouts/_ads.erb
<div id="ads">
  <%= yield :ads %>
<!-- Begin BidVertiser code --
<SCRIPT LANGUAGE="JavaScript1.1" SRC="http://bdv.bidvertiser.com/BidVertiser.dbm?pid=334544&bid=826792" type="text/javascript"></SCRIPT>
<noscript><a href="http://www.bidvertiser.com">affiliate program</a></noscript>
<!-- End BidVertiser code --> 

<!-- Begin Facebook code -->
<iframe src="http://www.facebook.com/plugins/likebox.php?id=174349512614081&amp;width=185&amp;connections=10&amp;stream=true&amp;header=true&amp;height=587" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:185px; height:587px; background-color: #ffffff;" ></iframe>
<!-- End Facebook code --> 
</div>

app/views/layouts/_left_nav.html.erb
<div id="nav">
  <ul>
		<li><%= link_to "Add an Internship", new_internship_path %></li>
		<li><%= link_to "New Internships", opportunities_path %></li>
		<li><%= link_to "New Reviews", reviews_path %></li>
		<li><%= link_to "Advanced Search", advanced_search_finds_path %></li>
		<!-- <li><%# link_to I18n.t("What's Hot"), hot_definitions_path %></li> -->
  </ul>

<div id="nightmare">Mission: Eliminate this...<br><a href="/images/nightmare.png" class="preview" title="Our mission: Eliminate this headache..."><img src="/images/nightmare_s.png" alt="gallery thumbnail" /></a><br>
And replace it with this...
<a href="/images/solution.png" class="preview" title="And replace it with this simple interface"><img src="/images/solution_s.png" alt="gallery thumbnail" /></a></div><br>
</div>

app/views/layouts/_sidebar.html.erb
<div id="sidebar">
  <%= render :partial => 'layouts/left_nav' %>
  <%= yield :sidebar %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head profile='http://gmpg.org/xfn/11'>
	<meta charset="utf-8" />
	<title>The Internship Database : <%= yield(:title) || "Find Internship Reviews or Opportunities" %></title>
	<meta name="google-site-verification" content="prpLgqQEKhoSzaS96o3aIPQ6u4czl74V1cvjAuNwkkk" />
	<!-- <meta name="google-site-verification" content="JW_hluXdWiBDeaLri74TwWs6B1mr6LMK3KleS75ZzZQ" /> -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/> 

</head>
</title>

<%= csrf_meta_tag %>
<%= stylesheet_link_tag 'reset' %>
<%= stylesheet_link_tag 'ui-lightness/jquery-ui-1.8.2.custom' %>
<%= stylesheet_link_tag 'authlogic-connect' %>
<%= stylesheet_link_tag 'form' %>
<% if is_mobile_device? %>
<%= stylesheet_link_tag 'handheld' %>
<% else %>
<% if browser_is? :ie %>
<%= stylesheet_link_tag 'application' %>
<% else %>
<%= stylesheet_link_tag 'application', :media => 'screen and (min-width: 800px), projection' %>
<%= stylesheet_link_tag 'handheld', :media => 'handheld, only screen and (max-width: 800px)' %>
<% end %>
<% end %>
<%= javascript_include_tag 'jquery-1.4.4.min' %>
<%= javascript_include_tag 'jquery-ui-1.8.2.custom.min' %>
<%= javascript_include_tag 'rails' %>
<%= javascript_include_tag 'application' %>
<%= javascript_include_tag 'authlogic-connect.js' %>
<%= javascript_include_tag 'jrails' %>
<%= javascript_include_tag 'image-preview' %>
<%= include_growlr.html_safe %>
<%= feedback_includes %>
<%= feedback_tab(:position => 'left') unless is_mobile_device? %>
<%# formtastic_stylesheet_link_tag %>

<% if protect_against_forgery? %>
<script type='text/javascript'>
//<![CDATA[
window._auth_token_name = "#{request_forgery_protection_token}";
window._auth_token = "#{form_authenticity_token}";
//]]>
</script>
<% end %>

<script src="http://static.ak.connect.facebook.com/js/api_lib/v0.4/FeatureLoader.js.php" type="text/javascript"></script>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-17217475-3']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
    <%# render :partial => "shared/head" %>
  </head>
  <body>
		<div id="topbar">
			<div id="topnav">
				<ul>
					<li id="homebutton"><%= link_to "Home", root_path %></li>
					<li><%# link_to "Hiatt", "http://www.brandeis.edu/hiatt/" %></li>
					<li><%# link_to "NACElink", "https://brandeisu-csm.symplicity.com/students/" %></li>
					<% if current_user %>
					<li><%= link_to "Internship List", internships_path %></li>
					<% end %>
					<% if current_user and current_user.admin %>
					<li><%= link_to "Approve", unapproved_path %></li>
					<% end %>
					<!-- <li><%# link_to I18n.t("Games"), games_path %></li> -->
				</ul>
			</div>

			<div id="usernav">
				<ul>
					<li><%= link_to "Advanced Search", advanced_search_path %></li>
					<li><%= link_to "New Internship", new_internship_path %></li>
					<% if current_user %>
					<li><%= link_to current_user.profile[:name], current_user %></li>
					<li><%= link_to "Logout", logout_path %></li>
					<%# end %>
					<% else %>
					<li><%= link_to "Register", new_user_session_path %></li>
					<% end %>
				</ul>
			</div>
		</div>
    <div id='wrapper'>
      <%= render :partial => "shared/logo" %>
			<%= render :partial => "shared/search" %>	
			<%= render :partial => 'layouts/sidebar' %>
					
        <div class='container'>
            <div class='content'>
              <%= yield %>
            </div>

		</div>
        
      <% if current_user %>
      <div class='actions'>
      	<%# link_to "Profile", current_user %>
				<%# link_to "Logout", logout_path %>
      </div>
      <% end %>
		<%= render :partial => 'layouts/ads' %>
		<div class='shadow'></div>
		
    </div>

		<div id="footer">
			<div id="info">
				<ul>
					<li id="terms"><%= link_to I18n.t("Terms of Service"), terms_path %></li>
					<li id="privacy"><%= link_to I18n.t("Privacy"), privacy_path %></li>
					<li id="about"><%= link_to I18n.t("About"), about_path %></li>
					<!-- <li id="contact"><%# link_to I18n.t("Contact"), contact_path %></li> -->
					<li id="resume"><%= link_to I18n.t("Resume"), resume_path %></li>
				</ul>
			</div>
			<!-- <p id="i18n">
							View this site in
							<span><%# link_to I18n.t("English"), :locale => "en" %></span>
							or
							<span><%# link_to I18n.t("Chinese"), :locale => "zh" %></span>
						</p> -->
			<p id="all-rights-reserved">
				<span><%= "© #{Time.now.year}. Murtaza Jafferji. All Rights Reserved." %></span>
			</p>
		</div>
		
  </body>
</html>